### ISSUE TITLE
Issue of deleting existing or adding a new user

### ISSUE THREAD

**Issue by jalalat** [entria/graphql-mongoose-loader#10]
1) Imagine a case where initially we fetched 20 users (sorted according to createdAt: -1). It got us the ids: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

2) rerun the app and fetch only 10 users initially. It will give us ids as expected: [1,2,3,4,5,6,7,8,9,10]
3) Delete the user with id: 2 and Load more 10 users
4) It will skip the user with id: 11 and fetch the users with ids: [12,13,14,15,16,17,18,19,20,21]

I have not tested the case with addition; i believe it may have similar effect in the opposite direction. Not sure.

**Comment by sibelius** [comment]
this can only be solved using subscriptions
