### ISSUE TITLE
Aggregate Loader - Allow to pass raw values to loader

### ISSUE THREAD

**Issue by JCMais** [entria/graphql-mongoose-loader#23]
Currently we are projecting only the `id` field and passing that to the loader:
https://github.com/entria/graphql-mongoose-loader/blob/master/src/ConnectionFromMongoAggregate.js#L54

We should allow the user to choose to receive the raw values, by adding a `raw` flag.

**Comment by sibelius** [comment]
it could be useful on `connectionFromMongoCursor` as well
