### ISSUE TITLE
what is it solving?

### ISSUE THREAD

**Issue by veeramarni** [entria/graphql-mongoose-loader#32]
If you could give some introduction to what actually it is solving would be great.

**Comment by jgcmarins** [comment]
It's solving relay/graphql connection approach.
**A full example can be found here**: https://github.com/entria/graphql-dataloader-boilerplate
**More about dataloader**: https://github.com/facebook/dataloader
**More about relay connections**: https://github.com/facebook/relay/blob/master/website/spec/Connections.md
You can also check [README](https://github.com/entria/graphql-mongoose-loader/blob/master/README.md) for more details.

**Comment by sibelius** [comment]
- [x] it implements dataloader for mongoose (batch requests and cache them)
- [x] it also implements a relay connection using mongoose cursors

**Comment by veeramarni** [comment]
Looks like it is more specific to relay, if we using `graphql-tools` will the batch requests and cache works?

**Comment by sibelius** [comment]
yep

you can use this with apollo or anything you'd like
