### ISSUE TITLE
`before: 0` sets the limit to 0, fetching *all* the data from mongo

### ISSUE THREAD

**Issue by channikhabra** [entria/graphql-mongoose-loader#34]
What do you suggest should be the response in that case? 

I think it should be an empty set of edges.

**Comment by sibelius** [comment]
Before and after are offsets, they set skip.

They should be strings

First and last that determine the limit to fetch from mongo

Before: 0 should be wrong

**Comment by sibelius** [comment]
Can you send a failing test case for this?

What is the value of first or last?

**Comment by jgcmarins** [comment]
I would love to see tests for this \o/

**Comment by channikhabra** [comment]
There you go: https://github.com/Veriown-CHS/graphql-mongoose-loader/commit/8a9f18a3c098619362b2fd12929d568bdc5d6bc9

**Comment by sibelius** [comment]
open as a pull request

**Comment by sibelius** [comment]
fixed here https://github.com/entria/graphql-mongoose-loader/pull/42
