### ISSUE TITLE
babel polyfill

### ISSUE THREAD

**Issue by AndreaBeggiato** [entria/graphql-mongoose-loader#5]
First of all, thanks for this package, you save me from a long boilerplate code.
BTW, I encounter a little problem using this package:

if you try to use this module without babel-polyfill package you encounter this error:
error:  ReferenceError: regeneratorRuntime is not defined

For a workaround you need to npm install babel-polyfill and require('babel-polyfill') in your app entry point.

Bye

**Comment by sibelius** [comment]
As we use `async await` syntax we should add a note on README.md about this

**Comment by lucasbento** [comment]
> As we use async await syntax we should add a note on README.md about this

Makes sense but I guess it's better to include it on the project and bundle it altogether.

**Comment by sibelius** [comment]
use land
