### ISSUE TITLE
create @types/graphql-mongoose-loader

### ISSUE THREAD

**Issue by jgcmarins** [entria/graphql-mongoose-loader#51]

**Comment by sibelius** [comment]
Can’t we have types in this repo already?

**Comment by jgcmarins** [comment]
sure

**Comment by jgcmarins** [comment]
- [ ] create `index.d.ts` files

**Comment by sibelius** [comment]
this https://github.com/entria/graphql-mongoose-loader/pull/49?

cc @julioxavierr

**Comment by gtolarc** [comment]
https://github.com/entria/graphql-mongoose-loader/commit/6675559c589432a8bd8833eea3e95fb542252d18#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 <- It doesn't work because of this commit. Can you get it back? @sibelius

**Comment by sibelius** [comment]
Some type checking is failing, can you try to fix and then I can release a new version with types

**Comment by gtolarc** [comment]
It would be okay to change it like this.
```
"build": "npm run build:babel",
-> "build": "npm run build:babel && npm run build:ts",
```

**Comment by sibelius** [comment]
Yes, but this only work if there is not typescript errors

**Comment by gtolarc** [comment]
There seems to be no type error in the latest version.
<img width="745" alt="스크린샷 2020-06-23 오전 10 19 32" src="https://user-images.githubusercontent.com/8623798/85350129-3bd90e00-b53b-11ea-8e7a-c344bd233273.png">

**Comment by sibelius** [comment]
I think @AugustoCalaca fixed them all

So we can do a new release with types

**Comment by sibelius** [comment]
this is failing for me
```jsx
node_modules/@types/mongodb/index"' has no exported member 'OptionalId'.

191       ? mongodb.OptionalId<CreateDocumentDefinition<D> & { _id: TId }>
                    ~~~~~~~~~~


Found 1 error.
```

**Comment by sibelius** [comment]
fixed
