### ISSUE TITLE
Tests not running

### ISSUE THREAD

**Issue by mauriciomutte** [entria/graphql-mongoose-loader#55]
Jest test not running. Does not show any errors. My OS is Ubuntu 19, I use node v12.6.0, yarn v1.17.3 and jest 23.5.0.

Below is the print of my terminal:

![image](https://user-images.githubusercontent.com/20569339/61173041-0fafc180-a564-11e9-9566-abbfb8061d05.png)

**Comment by sibelius** [comment]
I think this could be related to mongodb-memory-server

can you try to upgrade packages to understand what is going on?

try to run jest in debug mode

**Comment by mauriciomutte** [comment]
The problem was solved!

The reason for the problem was the _mongodb-memory-server_ that was outdated
