### ISSUE TITLE
Generalisation of loaded keys

### ISSUE THREAD

**Issue by kebou** [entria/graphql-mongoose-loader#60]
Hey guys,

Currently the `mongooseLoader` works only with the `_id` field, however it would be really useful to load data based on other keys as well (e.g. loading users by username).

It would only require a key field parameter in the mongooseLoader function. A possible implementation could be the folowing:
```typescript
export default async function mongooseLoader(
  model: Mongoose$Document,
  keys: ReadonlyArray<string>,
  lean: boolean = true,
  keyField: string = '_id'
) {
  const results = lean ? await model.find({ [keyField]: { $in: keys } }).lean() : await model.find({ [keyField]: { $in: keys } });

  return normalizeResults(keys, keyField, cacheKeyFn)(results);
}
```
The `lean` and `keyField` parameters could be moved to an `options` object, too.

Please share your thoughts on it!

**Comment by sibelius** [comment]
Do you have one dataloader per key?

are you using `prime` (https://github.com/graphql/dataloader#primekey-value) to keep all of them in sync?

we can go in the direction of this implementation, can you send a PR and add a test that uses this custom key?

**Comment by kebou** [comment]
Yes, I am using one dataloader per key and syning them with `prime`.

In my use case there are event tickets, which have two unique keys: the database ID and the barcode. I am using the ID to list the tickets in the admin app, and the barcode to check the validity of a ticket.

**Comment by sibelius** [comment]
fixed here https://github.com/entria/graphql-mongoose-loader/pull/61

tks

I'd like to see this in a blog post

**Comment by sibelius** [comment]
`4.2.0`
