### ISSUE TITLE
peerDependencies

### ISSUE THREAD

**Issue by maxaggedon** [entria/graphql-mongoose-loader#70]
Currently `package.json` says :
```
  "peerDependencies": {
    "graphql": "^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0"
  },
```

but I don't see any code directly relying on the `graphql` package...
On the contrary, `graphql-relay` and `mongoose` are `require`-d but not mentioned as peerDependencies.

**Comment by sibelius** [comment]
can you add those? and make `graphql: '*'` to accept any version of it?

**Comment by sibelius** [comment]
new version  4.3.1
