### ISSUE TITLE
TypeError: Cannot read property 'model' of undefined

### ISSUE THREAD

**Issue by davidrossjones** [entria/graphql-mongoose-loader#8]
When trying to use ConnectionFromMongoCursor I'm getting the error:

`TypeError: Cannot read property 'model' of undefined ...  graphql-mongoose-loader/lib/ConnectionFromMongoCursor.js:53:34`

Or this line:

`clonedCursor = cursor.model.find().merge(cursor);`

I've tried debugging and believe it's to do with the `getTotalCount` call but since this is async wrapped in the regeneratorRuntime its proving difficult. Is this a problem for anyone else?

Thank you.

**Comment by sibelius** [comment]
can you provide some snippet of how are you using the connectionFromMongoCursor?

**Comment by davidrossjones** [comment]
~~~
export const loadUsers = async (context: GraphQLContext, args: ConnectionArguments) => {
  const where = args.search ? { name: { $regex: new RegExp(`^${args.search}`, 'ig') } } : {};
  const users = UserModel.find(where, { _id: 1 }).sort({ createdAt: -1 });

  return connectionFromMongoCursor({
    cursor: users,
    context,
    args,
    loader: load,
  });
};
~~~
